### ISSUE TITLE
gradientLayer and cornerRadius

### ISSUE THREAD

**Issue by AMshev** [VadimZhukClass/ClassRoom#38]
Не работают вместе, только одно, есть ли возможность и применить фоном градиент, и сделать закругление углов?

**Comment by vadzimzhuk** [comment]
Работает же, что не так?

**Comment by AMshev** [comment]
<img width="1680" alt="Screenshot 2020-02-08 at 21 40 17" src="https://user-images.githubusercontent.com/59746592/74090383-ca348200-4abb-11ea-843a-d7a8919df595.png">

**Comment by AMshev** [comment]
Всё, разобрался )
