### ISSUE TITLE
Substring

### ISSUE THREAD

**Issue by March-tech** [VadimZhukClass/ClassRoom#51]
Можно дать пояснение, что тут происходит в коде?
<img width="789" alt="Снимок экрана 2020-02-13 в 18 10 54" src="https://user-images.githubusercontent.com/59727938/74448805-a80c7c80-4e8c-11ea-9047-cb4de02e6df2.png">

**Comment by March-tech** [comment]
а именно не понятна вторая и третья строка

**Comment by vadzimzhuk** [comment]
1. инициализируется строка
2. инициируется индекс для первого в строке элемента искомого (запятая)
3. с помощью индекса и диапазона инициируется сабстринг
4. сабстринг кастится в стринг
